#!/bin/zsh

# Verificación de argumento
if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <directory>"
  exit 1
fi

# Verificar si el directorio existe
if [ ! -d "$1" ]; then
    echo "El directorio especificado no existe."
    exit 1
fi

# Aplicar el comando 'scrub' a todos los archivos dentro del directorio
for file in "$1"/*; do
    if [ -f "$file" ]; then
        scrub -p dod "$file"
    fi
done

# Aplicar el comando 'shred' a todos los archivos dentro del directorio
for file in "$1"/*; do
    if [ -f "$file" ]; then
        shred -zun 10 -v "$file"
    fi
done

# Borrar el directorio después de ejecutar los comandos
rm -rf "$1"
