#!/bin/zsh

function rmk() {
  scrub -p dod "$1"
  shred -zun 10 -v "$1"
}

target_folder="${1}"

if [[ -z "$target_folder" ]]; then
  echo "Especificar ruta de la carpeta con el comando RUTA"
  exit 1
fi

for file in "$target_folder"/*; do
  if [[ -f "$file" ]]; then
    rmk "$file"
  fi
done
