#!/bin/zsh

# Verifica que se haya proporcionado una dirección IP como argumento
if [ $# -ne 1 ]; then
    echo "Por favor, proporciona una dirección IP como argumento."
    exit 1
fi

# Obtiene la dirección IP del argumento
subnet="$1"

# Ejecuta el comando nmap y filtra la salida
nmap -sn $subnet.0/24 | grep -oP '\d{1,3}(\.\d{1,3}){3}' | while read -r line; do
    echo "$line is up"
done

# Muestra el resumen final de nmap
nmap -sn $subnet.0/24 | grep -E 'Nmap done'
