#!/bin/zsh

# Instalar UFW si no está instalado
sudo apt-get update
sudo apt-get install ufw -y

# Habilitar UFW
sudo ufw enable

# Permitir el tráfico SSH en el puerto 22
sudo ufw allow 22

# Recargar UFW para aplicar los cambios
sudo ufw reload
